stages:
  data_ingestion:
    cmd: python main.py
    deps:
      - src/textSummarizer/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
      - config/params.yaml
    outs:
      - artifacts/data_ingestion/data.zip
